"
" Vundle
"

" Required options
set nocompatible
filetype off

" Set runtime path and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plugins
Plugin 'chriskempson/base16-vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'edkolev/tmuxline.vim'
Plugin 'fatih/vim-go'
Plugin 'plasticboy/vim-markdown'
Plugin 'rking/ag.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sensible'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Finish Vundle set up
call vundle#end()
filetype plugin indent on

"
" General settings
"

" Set up colors
set t_Co&
set background=dark
let base16colorspace = 256

colorscheme base16-ocean

" Remove duplicate information in status bar
set noshowcmd
set noshowmode

" Show line numbers
set number

" Use spaces for indendation
set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

" Show extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

" Filetype-specific settings
autocmd Filetype markdown setlocal ts=4 sw=4

" 80 character ruler
set textwidth=80
set colorcolumn=+1

" Open new split panes to right and bottom
set splitbelow
set splitright

"
" Key mappings
"

" Leader
let mapleader = "\<Space>"
nnoremap <Space> <nop>

let g:ctrlp_map = '<Leader>p'
nnoremap <Leader><space> :NERDTreeToggle<cr>

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

"
" Autocommands
"

augroup reload_vimrc " {
  autocmd!
  autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

"
" Plugin configuration
"

" ctrlp
"let g:ctrlp_user_command = 'ag -Q -l --nocolor --hidden -g "" %s'

" syntastic
let g:syntastic_check_on_open = 1

" vim-airline
let g:airline_theme = 'base16'
let g:airline_powerline_fonts = 1
let g:airline#extensions#ctrlp#color_template = 'normal'
let g:airline#extensions#tmuxline#enabled = 0

" vim-tmuxline
let g:tmuxline_preset = {
  \'a': '#T',
  \'win': ['#I', '#W'],
  \'cwin': ['#I', '#W'],
  \'z': '%R',
  \'options': {
    \'status-justify': 'right'}
  \}
