" Load pathogen
execute pathogen#infect()

" Set up colors
set t_Co&
set background=dark
let base16colorspace=256

colorscheme base16-ocean

" Disable folding in markdown plugin
let g:vim_markdown_folding_disabled = 1

" Enable powerline symbols in statusbar
let g:airline_powerline_fonts = 1

" Tmuxline configuration
let g:tmuxline_preset = {
	\'a': '#T',
	\'win': ['#I', '#W'],
	\'cwin': ['#I', '#W'],
	\'z': '%R',
	\'options': {
		\'status-justify': 'right'}
	\}

" Disable airline-tmuxline integration
let g:airline#extensions#tmuxline#enabled = 0

" Remove duplicate information in status bar
set noshowcmd
set noshowmode

" Show line numbers
set number
