"
" General settings
"

" Load pathogen
execute pathogen#infect()

" Set up colors
set t_Co&
set background=dark
let base16colorspace = 256

colorscheme base16-ocean

" Remove duplicate information in status bar
set noshowcmd
set noshowmode

" Show line numbers
set number

" Use spaces for indendation
set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

" Show extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

" Filetype-specific settings
autocmd Filetype markdown setlocal ts=4 sw=4

" 80 character ruler
set textwidth=80
set colorcolumn=+1

" Open new split panes to right and bottom
set splitbelow
set splitright

"
" Key mappings
"

let mapleader = " "

"
" Plugin configuration
"

" vim-airline
let g:airline_theme = 'base16'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tmuxline#enabled = 0

" vim-tmuxline
let g:tmuxline_preset = {
  \'a': '#T',
  \'win': ['#I', '#W'],
  \'cwin': ['#I', '#W'],
  \'z': '%R',
  \'options': {
    \'status-justify': 'right'}
  \}
