#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source secrets
if [[ -s "${ZDOTDIR:-$HOME}/.zshsecret" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshsecret"
fi

# GOPATH
export GOPATH=${HOME}/Development/go
